### ISSUE TITLE
Error on sarif results 'export' 

### ISSUE THREAD

**Issue by Izocel** [doyensec/electronegativity-action#2]
## Trying to add the sarif to a repo folder... Error: mkdir: cannot create directory ‘../results’: File exists
- I think I misinterpreted the serif feature your providing, its not for file 'push' but it will show results in the action results ?
- If so , can we 'push' the results.serif to the repo with this action ?
- Also while im there will this engage as an infinite loop (because of a file 'push') ? LMAO

### Wondering if its because of `github/codeql-action/analyze@v2` as already created ../results  ???

**CodeQl.yaml**
```yml
name: "CodeQL"

on:
  create:
    branches : ["dev", "releases/**"]
  push:
    branches: ["dev", "releases/**"]
  pull_request:
    branches: ["dev", "releases/**"]

jobs:
  analyze:
    name: Analyze/Build
    runs-on: ${{ matrix.os }}
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      matrix:
        node-version: [18.x]
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
        env:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:${{matrix.language}}"
       

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        env:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: doyensec/electronegativity-action@v1.1
      
      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ./opsec/${{ matrix.os }}/results-${{ github.event.repository.updated_at}}.sarif

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          github_token: ${{ secrets.github_token }}

          # Release the app after building If the branch tsarts with "release"
          release: ${{ startsWith(github.ref, 'refs/heads/release') }}
```
